[WIP] Feat/auth cookie update
supabase/gotrue-js pull request #211
Opened 2022-01-19 15:26 UTC by thorwebdev

Try to read tokens from cookies/headers if possible.

For a while when local testing the redirect request to my API route would log as

```
req.headers {
  host: 'localhost:3000',
  connection: 'keep-alive',
  'upgrade-insecure-requests': '1',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'sec-fetch-site': 'cross-site',
  'sec-fetch-mode': 'navigate',
  'sec-fetch-user': '?1',
  'sec-fetch-dest': 'document',
  'sec-ch-ua': '" Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"',
  'sec-ch-ua-mobile': '?0',
  'sec-ch-ua-platform': '"macOS"',
  'accept-encoding': 'gzip, deflate, br',
  'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8',
  cookie: 'sb-access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjQyNjA0MzI1LCJzdWIiOiJjYTMyNzhhZS0xNGMxLTQ4NzktYjVkYi01ZGI1NGIyNTVkZTYiLCJlbWFpbCI6InRob3JzdGVuLnNjaGFlZmZAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJnb29nbGUiLCJwcm92aWRlcnMiOlsiZ29vZ2xlIl19LCJ1c2VyX21ldGFkYXRhIjp7ImF2YXRhcl91cmwiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS0vQU9oMTRHaktkZi1rVlVIbkk2Y05zS0h1SDVjck5yZHVUN2FvSnhscnlZNXBNZms9czk2LWMiLCJlbWFpbCI6InRob3JzdGVuLnNjaGFlZmZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZ1bGxfbmFtZSI6IlRob3JzdGVuIFNjaGFlZmYiLCJpc3MiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS91c2VyaW5mby92Mi9tZSIsIm5hbWUiOiJUaG9yc3RlbiBTY2hhZWZmIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hLS9BT2gxNEdqS2RmLWtWVUhuSTZjTnNLSHVINWNyTnJkdVQ3YW9KeGxyeVk1cE1maz1zOTYtYyIsInByb3ZpZGVyX2lkIjoiMTE3ODYzNjY4Nzc3ODk2NjQ4Mzg1Iiwic3ViIjoiMTE3ODYzNjY4Nzc3ODk2NjQ4Mzg1In0sInJvbGUiOiJhdXRoZW50aWNhdGVkIn0.iuW2lUKppZWqOzkezYDuVa5H8sMrwFc7X3OlRP6JAlI; sb-refresh-token=0F__bWZSBVVs_UJxnbPN7w',
  'if-none-match': '"b-Ai2R8hgEarLmHKwesT1qcY913ys"'
}
req.cookies {
  'sb-access-token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjQyNjA0MzI1LCJzdWIiOiJjYTMyNzhhZS0xNGMxLTQ4NzktYjVkYi01ZGI1NGIyNTVkZTYiLCJlbWFpbCI6InRob3JzdGVuLnNjaGFlZmZAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJnb29nbGUiLCJwcm92aWRlcnMiOlsiZ29vZ2xlIl19LCJ1c2VyX21ldGFkYXRhIjp7ImF2YXRhcl91cmwiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS0vQU9oMTRHaktkZi1rVlVIbkk2Y05zS0h1SDVjck5yZHVUN2FvSnhscnlZNXBNZms9czk2LWMiLCJlbWFpbCI6InRob3JzdGVuLnNjaGFlZmZAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZ1bGxfbmFtZSI6IlRob3JzdGVuIFNjaGFlZmYiLCJpc3MiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS91c2VyaW5mby92Mi9tZSIsIm5hbWUiOiJUaG9yc3RlbiBTY2hhZWZmIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hLS9BT2gxNEdqS2RmLWtWVUhuSTZjTnNLSHVINWNyTnJkdVQ3YW9KeGxyeVk1cE1maz1zOTYtYyIsInByb3ZpZGVyX2lkIjoiMTE3ODYzNjY4Nzc3ODk2NjQ4Mzg1Iiwic3ViIjoiMTE3ODYzNjY4Nzc3ODk2NjQ4Mzg1In0sInJvbGUiOiJhdXRoZW50aWNhdGVkIn0.iuW2lUKppZWqOzkezYDuVa5H8sMrwFc7X3OlRP6JAlI',
  'sb-refresh-token': '0F__bWZSBVVs_UJxnbPN7w'
}
```

That's what I based the implementation on. However eventually the logs returned to it being empty:

```
req.headers {
  host: 'localhost:3000',
  connection: 'keep-alive',
  'upgrade-insecure-requests': '1',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'sec-fetch-site': 'cross-site',
  'sec-fetch-mode': 'navigate',
  'sec-fetch-user': '?1',
  'sec-fetch-dest': 'document',
  'sec-ch-ua': '" Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"',
  'sec-ch-ua-mobile': '?0',
  'sec-ch-ua-platform': '"macOS"',
  referer: 'http://localhost:3000/',
  'accept-encoding': 'gzip, deflate, br',
  'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8',
  'if-none-match': '"b-Ai2R8hgEarLmHKwesT1qcY913ys"'
}
req.cookies {}
```

At this point I have no idea why 😕 

@dthyresson @kangmingtay anything that stands out to you?

2022-01-19 15:39 UTC, dthyresson commented
> anything that stands out to you?

@thorwebdev What do the response headers look like?

When you say request, what is making the request and what is receiving the request?

2022-01-19 15:48 UTC, thorwebdev commented
Gotrue is making the request via http.Redirect in the callback route. 

Next.js api route is receiving the request.

2022-01-19 15:57 UTC, dthyresson commented
> Gotrue is making the request via http.Redirect in the callback route.
> 
> Next.js api route is receiving the request.

When in doubt .... CORS?

Also, see `Preflight Requests Block Cookies`: https://medium.com/swlh/7-keys-to-the-mystery-of-a-missing-cookie-fdf22b012f09 


With RedwoodJS's cookie dbAuth provider, ran into a case where CORS needed to be set https://github.com/redwoodjs/redwood/pull/4150

2022-01-19 18:16 UTC, bnjmnt4n commented
Based on my understanding of cookies, this approach doesn't work since the cookies returned by GoTrue will be associated with the GoTrue domain. GoTrue redirects to the given API route which is on a different domain. The browser will not send the cookies associated with the GoTrue domain to any other domain since that would trivially lead to exploitation.

2022-01-20 08:52 UTC, thorwebdev commented
@bnjmnt4n yes, you are correct, this approach only works if gotrue is running on the same domain.

2022-01-20 16:04 UTC, kangmingtay requested changes

2022-01-20 17:15 UTC, thorwebdev commented
@dthyresson would you mind testing the `getAuthCookieString` approach with your Fastify app?

2022-01-20 18:02 UTC, thorwebdev commented on src/GoTrueApi.ts
> +      return { token: access_token, user, data: user, error: null }
For you most certainly ;)

2022-01-21 02:43 UTC, alaister commented
Hey,
I'm missing a lot of context here, but I'm keen to see token refreshing for SSR type web apps.

What happens when the cookie tokens and the client side tokens become out of sync? For example when the token gets refreshed server side, and then the client also tries to refresh after the page loads.
Does the GoTrue backend allow the same refresh token to be used multiple times within a short period of time, making this a non-issue?

I spun up this PR locally, logged in, and then waited for my session to expire on the `/profile` route. After refreshing, the token refreshed server side no problem, but upon navigating back to the `/` route, it seemed I was logged out client side.

Please let me know if I can help out!

2022-01-21 03:41 UTC, thorwebdev commented
Yes, very good point @alaister, you will need to decide what your source of truth is. E.g. here you will always need to fetch the user from the server, e.g. via https://github.com/supabase/gotrue-js/blob/feat/auth-cookie-update/example/next-auth0-migration-example/pages/api/me.js

In the future we're planning to move fully away from using localStorage, but there are a couple things that need to happen first.

2022-01-24 15:28 UTC, kangmingtay approved these changes

2022-01-25 02:36 UTC, merged