chore: adds notion and alphabetize
supabase/gotrue-js pull request #216
Opened 2022-01-27 04:03 UTC by awalias

to match https://github.com/supabase/supabase/pull/5018#pullrequestreview-864341046

2022-01-27 04:19 UTC, soedirgo approved these changes

2022-01-27 06:11 UTC, kangmingtay commented
we also have 2 new sms providers (vonage & textlocal) and another oauth provider (linkedin), can we add those in as well?

2022-01-27 06:12 UTC, kangmingtay requested changes

2022-01-27 06:12 UTC, kangmingtay commented on src/lib/types.ts
>  export type Provider =
we also have 2 new sms providers (vonage & textlocal) and another oauth provider (linkedin), can we add those in as well?

2022-02-09 01:28 UTC, kangmingtay approved these changes

2022-02-09 02:31 UTC, merged