fix: add warning if redirect_to is used for non-oauth sign-ups / sign-ins
supabase/gotrue-js pull request #254
Opened 2022-03-22 12:31 UTC by kangmingtay

## What kind of change does this PR introduce?
* `redirect_to` doesn't work for non-oauth sign-ups / sign-ins because those requests are POST requests. This means that we cannot redirect them without converting them into a GET request which would result in losing the response body.

2022-03-22 12:32 UTC, kangmingtay commented on src/GoTrueClient.ts
> +      Logger.warn('redirectTo param will only redirect OAuth logins.')
not sure why we added a `redirect_to` to the `signUp` method - it won't work here as well since these are all POST requests

2022-03-22 12:53 UTC, kiwicopple requested changes
Sorry @kangmingtay - we can't include pino in these libraries because we are trying to keep them as small as possible. Perhaps just a regular console.warn will suffice?

2022-03-22 16:18 UTC, thorwebdev commented
Are we getting a lot of support requests about this? I personally haven't seen any, so wondering if this is really necessary.

2022-03-22 16:25 UTC, kangmingtay commented
> Are we getting a lot of support requests about this? I personally haven't seen any, so wondering if this is really necessary.

yeah i've seen this appear quite a few times on the github discussions / issues - it also seems confusing that the `redirect_to` param only applies when you use oauth and not other forms of authentication

2022-03-23 20:33 UTC, GaryAustin1 commented
A document note on it would would be enough IMO.  I've seen it asked several times in Discord and have had to answer "I don't think that does anything"  for email/password, as I never found a clear answer, even in the source.
```
      if (email && password) {
        return this._handleEmailSignIn(email, password, {
          redirectTo: options.redirectTo,
        })
```
So you have to go dig thru gotrue to figure out the answer, or try it (which I did, so I could give an educated answer).

2022-03-26 14:26 UTC, kangmingtay commented
thanks for the feedback everyone! i've corrected the typedocs so it's clearer now

2022-03-27 18:44 UTC, kiwicopple approved these changes

2022-03-27 22:02 UTC, merged