fix: add forgotten `data` option for sign ins
supabase/gotrue-js pull request #512
Opened 2022-10-19 16:09 UTC by hf

`data` options were forgotten for some sign in methods.

2022-10-19 16:10 UTC, J0 approved these changes

2022-10-21 03:36 UTC, kangmingtay requested changes
~we also need to add this to `signInWIthOtp` right?~ 

edit: just checked, it's already there

2022-10-21 03:40 UTC, kangmingtay approved these changes

2022-10-21 03:40 UTC, merged

2022-10-21 06:15 UTC, kangmingtay commented on src/lib/types.ts
> +        data?: object
actually `SignInWithPassword` doesn't accept a data option in gotrue